vim.pack.add(
	{"https://github.com/nickjvandyke/opencode.nvim"})
local opencode = require("opencode")
vim.keymap.set("n", "<leader>on", function()
	opencode.command("session.new")
end)
vim.keymap.set("n", "<leader>oa", function()
	opencode.ask("")
end)
vim.keymap.set("n", "<leader>ob", function()
	opencode.ask("@buffer ")
end)
vim.keymap.set("v", "<leader>oa", function()
	opencode.ask("@this ")
end)
