vim.pack.add({ "https://github.com/nvim-lua/plenary.nvim", "https://github.com/nvim-telescope/telescope.nvim" })
local builtin = require("telescope.builtin")
vim.keymap.set("n", "ff", builtin.find_files, { desc = "Telescope find files" })
vim.keymap.set("n", "fg", builtin.live_grep, { desc = "Telescope live grep" })
vim.keymap.set("n", "fb", builtin.buffers, { desc = "Telescope buffers" })
vim.keymap.set("n", "fh", builtin.help_tags, { desc = "Telescope help tags" })
vim.keymap.set("n", "fs", "<cmd>Telescope lsp_document_symbols<cr>")
